% Examples of using the Johnson System of Distributions (Johnson Curves)
% 
% by David L. Jones, Apr-2014
%
% This file is part of the 'JOHNSON CURVE TOOLBOX FOR MATLAB'
% and is released under the BSD 2-clause license.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                  SB Curve -  example 2 from Johnson (1949):                  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% This example considers the age of 631,682 mothers when they gave birth in
% Australia from 1922-1926 and follows Johnson's (1949) example 2 using data
% from his table 5.
% 
% Johnson, N. L. 1949. Systems of frequency curves generated by methods of
%  translation. Biometrika 36: 149-176.

% Clear the workspace:
clc; clear all; close all;

% Load the data:
X = load('age_at_birth.dat');

% Add some random noise:
rng('default'); % reset for repeatability
amt = mean(diff(unique(X)))/2;
X   = X + random('uniform',-amt,amt,size(X,1),1);

% Fit a Johnson Curve:
jsn_m = f_johnson_fit(X,'M',2); % fit using moments
jsn_q = f_johnson_fit(X,'Q',0); % fit using quantiles
[jsn_m.coef' jsn_q.coef']       % compare estimates
% ans =
% 
%       0.54493      0.49648
%        1.2309       1.1573
%        14.966       15.595
%        36.007       34.089

% -> These are similar to Johnson's (1949) results as his parameters were
% [0.5918 1.2536 15.0 36.5] for [gamma delta xi lambda], respectively. However,
% he did not add random noise to his data.

% Compare the fit of the Johnson 'SB' distribution with that of, say, a two
% parameter Gamma distribution defined by a = 22.504 and b = 1.3122:
% 
% Show measures of fit for Gamma distribution (calculated elswehere):
% gamma.nLL  = 2.0419e+06; % negative log-likelihood
% gamma.AIC  = 4.0838e+06; % Akaike's Information Criterion
% gamma.AICc = 4.0838e+06  % AIC corrected for sample size
% gamma.BIC  = 4.0839e+06; % Schwarz's Bayesian Information Criterion

% Calculate measures of fit for Johnson 'SB' distribution:
nLL            = f_johnson_lik(X,jsn_m.coef,jsn_m.type);
[AIC,AICc,BIC] = f_johnson_aic(X,jsn_m.coef,jsn_m.type);
[nLL AIC AICc BIC]'
% ans =
% 
%     2.031e+06
%    4.0621e+06
%    4.0621e+06
%    4.0621e+06
% 
% - For all of these goodness-of-fit measures smaller is better, which indicate
%   in this case the Johnson 'SB' distribution provides a better fit to the data
%   than the Gamma distribution.

% What the probability a mother was 32 years old or less?
prob = f_johnson_cdf(32,jsn_m.coef,jsn_m.type)
% prob = 0.6599

% How likely was it for one of the mothers to be 42 years or older?
pval = 1 - f_johnson_cdf(42,jsn_m.coef,jsn_m.type)
% pval = 0.028561
% -> not very likely

% What range of ages constitutes 95% of the mothers that gave birth: 
f_johnson_inv([0.025 0.975]',jsn_m.coef,jsn_m.type)
% ans = 19.128 42.312
% -> 95% of the mothers were between 19 and 42 years old.

% Draw a random sample of 1000 values from the Johnson SB distribution:
R = f_johnson_rnd(jsn_m.coef,jsn_m.type,100,1);
figure; hist(R,25);
xlabel('Age');
ylabel('Frequency');
title('Johnson SB distribution');

% Transform Johnson to normal variates:
Z = f_johnson_y2z(R,jsn_m.coef,jsn_m.type);
figure; hist(Z,25);
xlabel('Age');
ylabel('Frequency');
title('Standard normal distribution');



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                      SU Curve - example 3 from Johnson (1949):               %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% This example considers the length (in mm) of 9440 beans and follows Johnson's
% (1949) example 3 using data from his table 6.

% Clear the workspace:
clc; clear all; close all;

% Load the data:
X = load('bean_length.dat');

% Add some random noise:
rng('default'); % reset for repeatability
amt = mean(diff(unique(X)))/2;
X   = X + random('uniform',-amt,amt,size(X,1),1);

% Fit a Johnson Curve:
jsn_m = f_johnson_fit(X,'M',1); % fit using moments
jsn_q = f_johnson_fit(X,'Q',0); % fit using quantiles
[jsn_m.coef' jsn_q.coef']       % compare estimates
% ans =
% 
%        2.1903       1.7471
%        2.6806       2.5862
%        16.039       15.778
%        1.6742       1.7481

% Note: Both methods produced results similar to what Johnson (1949) obtained
% using a graphical calculator (i.e., an abaque). Any difference between his
% results and those show here using the 'M' method are largely due to my adding
% random noise to the input data.

% Compare the fit of the Johnson 'SU' distribution with that of, say, a two
% parameter Weibull distribution defined by a = 14.81 and b = 18.594:
% 
% Show measures of fit for Weibull distribution (calculated elswehere):
% weibull.nLL = 12259
% weibull.AIC = 24522
% weibull.AICc = 24522
% weibull.BIC  = 24536

% Calculate measures of fit for Johnson 'SU' distribution:
nLL            = f_johnson_lik(X,jsn_m.coef,jsn_m.type);
[AIC,AICc,BIC] = f_johnson_aic(X,jsn_m.coef,jsn_m.type);
[nLL AIC AICc BIC]'
% ans =
% 
%         12174
%         24355
%         24355
%         24384

% -> Again, smaller is better so all of these goodness-of-fit measures indicate 
%    the Johnson 'SU' distribution provides a better fit to the data than the
%    Weibull distribution.



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                  SU Curve - example 4 from Johnson (1949):                   %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% This example considers the breadth (in mm) of 9440 beans and follows Johnson's
% (1949) example 4 using data from his table 7.

% Clear the workspace:
clc; clear all; close all;

% Load the data:
X = load('bean_breadth.dat');

% Add some random noise:
rng('default'); % reset for repeatability
amt = mean(diff(unique(X)))/2;
X   = X + random('uniform',-amt,amt,size(X,1),1);

% Fit a Johnson Curve:
jsn_m = f_johnson_fit(X,'M',1); % fit using moments
jsn_q = f_johnson_fit(X,'Q',0); % fit using quantiles
[jsn_m.coef' jsn_q.coef']       % compare estimates
% ans =
% 
%        1.7011       1.1417
%        3.5848       2.8446
%        8.5336       8.3572
%        1.0902      0.87667

% Note: Both methods produced results similar to what Johnson (1949) obtained
% using an abaque, though some differences arise due to our adding random noise
% to the data and his reading incorrect values for delta and gamma off his
% abaque (for details see: Draper, J. 1952. Properties of distributions
% resulting from certain simple transformations of the normal distribution.
% Biometrika 39(3/4):290-301).

% Compare the fit of the Johnson 'SU' distribution with that of, say, a two
% parameter logistic distribution defined by mu = 7.9867 and sigma = 0.19854:
% 
% Show measures of fit for Weibull distribution (calculated elswehere):
% logistic.nll  = 3563.2;
% logistic.BIC  = 7144.7;
% logistic.AIC  = 7130.4;
% logistic.AICc = 7130.4;

% Calculate measures of fit for Johnson 'SU' distribution:
nLL            = f_johnson_lik(X,jsn_m.coef,jsn_m.type);
[AIC,AICc,BIC] = f_johnson_aic(X,jsn_m.coef,jsn_m.type);
[nLL AIC AICc BIC]'
%  ans =
% 
%        3474.5
%          6957
%          6957
%        6985.6
% 
% -> Smaller is better so all of these goodness-of-fit measures indicate the
%    Johnson 'SU' distribution provides a better fit to the data than the
%    Logistic distribution.



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                  SB Curve - example 1 from Johnson (1949):                   %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% This example considers the degree of cloudiness recorded at Greenwich over a
% 13 year period as measured on a scale from 0-10 and follows Johnson's (1949)
% example 2 using data from his table 4.

% Clear the workspace:
clc; clear all; close all;

% Load the data:
X = load('clouds.dat');

% Add some random noise:
rng('default'); % reset for repeatability
amt = mean(diff(unique(X)))/2;
mv  = max(X);
X   = X + random('uniform',-amt,amt,size(X,1),1);
X   = unifcdf(X,min(X),max(X))*mv;

% Visualize the data:
figure; set(gcf,'color','w');
hist(X,100);
h = findobj(gca,'Type','patch');
set(h,'FaceColor',[1 1 1]*0.65,'EdgeColor','none')
title({'Cloudiness at Greenwich','1890-1900, 1902-1904'});
xlabel('Cloudiness (0-10)')
ylabel('Frequency (days)');

% Fit a Johnson Curve:
jsn_m = f_johnson_fit(X,'M',2); % fit using moments
jsn_q = f_johnson_fit(X,'Q',0); % fit using quantiles
[jsn_m.coef' jsn_q.coef']       % compare estimates
% ans =
%      -0.29231     -0.24137
%       0.21551      0.26568
%       0.29798      0.23141
%        9.3985       9.6336

% -> Overall, the skies at Greenwich tended to be either completely cloudy or
%    with very little cloudiness, with intermediate levels occurring on much
%    rarer occasions.
