Description of nt_cov
Home > NoiseTools > nt_cov.m
nt_cov
PURPOSE
[c,tw]=nt_cov(x,shifts,w) - time shift covariance
SYNOPSIS
function [c,tw]=nt_cov(x,shifts,w);
DESCRIPTION
[c,tw]=nt_cov(x,shifts,w) - time shift covariance
  c: covariance matrix
  tw: total weight (c/tw is normalized covariance)
  x: data
  shifts: array of time shifts (must be non-negative)
  w: weights
 If SHIFTS==[0], this function calculates the covariance matrix of X,
 weighted by W.  In the general case it calculates the covariance matrix
 of time-shifted X.
 X can be 1D, 2D or 3D.  It can also be a cell array.
 W can be 1D (if X is 1D or 2D) or 2D (if X is 3D). The same weight is
 applied to each column.
 Output is a 2D matrix with dimensions (ncols(X)*numel(SHIFTS))^2.
 It is made up of an ncols(X)*ncols(X) matrix of submatrices, each of
 dimensions numel(SHIFTS)*numel(SHIFTS).
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
nt_demean [y,mn]=nt_demean(x,w) - remove weighted mean over cols
nt_multishift z=nt_multishift(x,shifts,amplitudes) - apply multiple shifts to matrix
nt_vecmult y=nt_vecmult(x,v) - multiply all rows or columns of matrix by vector
This function is called by:
nt_bias_cluster [c0,c1,A,todss,pwr0,pwr1]=nt_bias_cluster(x,dsr,flags) - cluster covariance
nt_bias_fft [c0,c1]=nt_bias_fft(x,freq,nfft) - covariance with and w/o filter bias
nt_bias_filter [c0,c1]=nt_bias_filter(x,B,A) - covariance with and w/o filter bias
nt_bias_hi_amp [c0,c1]=bias_hi_amp(x,exponent) - covariance with and without hi-amp bias
nt_cluster_jd [IDX,todss,SCORE]=nt_cluster_jd(x,dsr,smooth,flags,init,verbose) - cluster with joint diagonalization
nt_cluster_jd_old [IDX,todss,SCORE]=nt_cluster_jd2(x,dsr,flags,init) - cluster with joint diagonalization
nt_dss1 [todss,pwr0,pwr1]=nt_dss1(x,w,keep1,keep2,sns_flag) - evoked-biased DSS denoising
nt_enforce_stationarity y=nt_enforce_stationarity(x,DSR,thresh) - locally project out non-stationary components
nt_kurtosis [todss,K]=nt_kurtosis(x,nIterations,exponent,w,smooth)- find high-kurtosis components
nt_pca [z,idx]=nt_pca(x,shifts,nkeep,threshold,w) - time-shift pca
nt_pca0 [topcs,pwr]=nt_pca0(x,shifts,nkeep,threshold,w) - time-shift pca
nt_pca_nodemean [z,idx]=nt_pca_nodemean(x,shifts,keep,threshold,w) - time-shift pca
nt_sns y=nt_sns(x,nneigbors,skip,w) - sensor noise suppression
nt_split_jd [idx,score_vector,todss]=nt_split_dss(x,thresh,depth) - segmentation based on joint diagonalization
nt_star [y,w,ww]=nt_star(x,thresh,closest,depth) - sensor noise suppression, new version
nt_tsr [y,idx,w]=nt_tsr(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_tsr_nodemean [y,idx,w]=nt_tsr_nodemean(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_tsregress [z,idx]=nt_tsregress(x,y,shifts,xw,yw,keep,threshold) - time-shift regression
SOURCE CODE
function [c,tw]=nt_cov(x,shifts,w);
%[c,tw]=nt_cov(x,shifts,w) - time shift covariance
%
%  c: covariance matrix
%  tw: total weight (c/tw is normalized covariance)
%
%  x: data
%  shifts: array of time shifts (must be non-negative)
%  w: weights
%
% If SHIFTS==[0], this function calculates the covariance matrix of X,
% weighted by W.  In the general case it calculates the covariance matrix
% of time-shifted X.
%
% X can be 1D, 2D or 3D.  It can also be a cell array.
% W can be 1D (if X is 1D or 2D) or 2D (if X is 3D). The same weight is
% applied to each column.
%
% Output is a 2D matrix with dimensions (ncols(X)*numel(SHIFTS))^2.
% It is made up of an ncols(X)*ncols(X) matrix of submatrices, each of
% dimensions numel(SHIFTS)*numel(SHIFTS).
%
% NoiseTools
if nargin<4||isempty(demean_flag); demean_flag=0; end
if nargin<3; w=[]; end;
if nargin<2||isempty(shifts); shifts=0; end;
if prod(size(x))==0; error('data empty'); end
if min(shifts)<0; error('shifts should be non-negative'); end
shifts=shifts(:);           % --> column vector
nshifts=numel(shifts);
if isempty(w)
    % no weights
    if isnumeric(x)
        [m,n,o]=size(x);
        c=zeros(n*nshifts);
        for k=1:o
            xx=nt_multishift(x(:,:,k),shifts);
            if demean_flag
                xx=nt_demean(xx);
            end
            c=c+xx'*xx;
        end
        tw=size(xx,1)*o;
    else
        [m,n]=size(x{1});
        o=length(x);
        c=zeros(n*nshifts);
        for k=1:o;
            xx=nt_multishift(x{k}(:,:),shifts);
            if demean_flag
                xx=nt_demean(xx);
            end
            c=c+xx'*xx;
        end
        tw=size(xx,1)*o;
    end
else
    % weights
    if size(w,2)>1; error('w should have single column'); end
    if isnumeric(x)
        [m,n,o]=size(x);
        c=zeros(n*nshifts);
        for k=1:o
            if ~all(shifts == [0]);
                xx=nt_multishift(x(:,:,k),shifts);
                ww=nt_multishift(w(:,:,k),shifts);
                ww=min(ww,[],2);
            else
                xx=x(:,:,k); ww=w(:,:,k);
            end
            xx=nt_vecmult(xx,ww);
            if demean_flag; xx=nt_demean(xx); end
            c=c+xx'*xx;
        end
        tw=sum(w(:));
    else
        c=zeros(n*nshifts);
        [m,n]=size(x{1});
        o=length(x);
        for k=1:o
            if ~all(shifts == [0]);
                xx=nt_multishift(x{k}(:,:),shifts);
                ww=nt_multishift(w{k}(:,:),shifts);
                ww=min(ww,[],2);
            else
                xx=x{k}(:,:); ww=w{k}(:,:);
            end
            xx=nt_vecmult(xx,ww);
            if demean_flag; xx=nt_demean(xx); end
            c=c+xx'*xx;
        end
        tw=sum(w(:));
    end
end