Description of nt_demean
Home > NoiseTools > nt_demean.m
nt_demean
PURPOSE
[y,mn]=nt_demean(x,w) - remove weighted mean over cols
SYNOPSIS
function [x,mn]=nt_demean(x,w)
DESCRIPTION
[y,mn]=nt_demean(x,w) - remove weighted mean over cols
  w is optional
  if w is a vector with fewer samples than size(x,1), it is interpreted as
  a vector of indices to be set to 1, the others being set to 0.
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
nt_fold y=fold(x,epochsize) - fold 2D to 3D
nt_greetings nt_greetings - display message the first time the toolbox is used
nt_unfold y=nt_fold(x) - unfold 3D to 2D
nt_vecadd y=nt_vecadd(x,v) - add vector to all rows or columns of matrix
nt_vecmult y=nt_vecmult(x,v) - multiply all rows or columns of matrix by vector
This function is called by:
nt_cov [c,tw]=nt_cov(x,shifts,w) - time shift covariance
nt_demean2 y=nt_demean2(x,w) - remove mean of each row and page
nt_detrend y=nt_detrend(x,order,w,basis) - remove polynomial or sinusoidal trend
nt_find_outliers w=nt_find_outliers(x,toobig1,toobig2) - find outliers (glitches, etc.).
nt_kurtosis [todss,K]=nt_kurtosis(x,nIterations,exponent,w,smooth)- find high-kurtosis components
nt_repeatability [score]=nt_repeatability(x,demean_flag) - repeatability score
nt_sgram [s,f,t]=nt_sgram(x,window,noverlap,nfft,sr,flags) - spectrogram
nt_sns y=nt_sns(x,nneigbors,skip,w) - sensor noise suppression
nt_split [idx,score_vector,score]=nt_split(x,depth,thresh,guard) - split time series into intervals
nt_split_jd [idx,score_vector,todss]=nt_split_dss(x,thresh,depth) - segmentation based on joint diagonalization
nt_star [y,w,ww]=nt_star(x,thresh,closest,depth) - sensor noise suppression, new version
nt_tsr [y,idx,w]=nt_tsr(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_tsregress [z,idx]=nt_tsregress(x,y,shifts,xw,yw,keep,threshold) - time-shift regression
SOURCE CODE
function [x,mn]=nt_demean(x,w)
%[y,mn]=nt_demean(x,w) - remove weighted mean over cols
%
%  w is optional
%
%  if w is a vector with fewer samples than size(x,1), it is interpreted as
%  a vector of indices to be set to 1, the others being set to 0.
%
% NoiseTools
if nargin<2; w=[]; end
if nargin<1; error('!');end
nt_greetings;
if ~isempty(w) && numel(w)<size(x,1)
    w=w(:);
    % interpret w as array of indices to set to 1
    if min(w)<1 || max(w)>size(x,1);
        error('w interpreted as indices but values are out of range');
    end
    ww=zeros(size(x,1),1);
    ww(w)=1;
    w=ww;
end
if size(w,3)~=size(x,3);
    if size(w,3)==1 && size(x,3)~=1;
        w=repmat(w,[1,1,size(x,3)]);
    else
        error('W should have same npages as X, or else 1');
    end
end
[m,n,o]=size(x);
x=nt_unfold(x);
if isempty(w);
    mn=mean(double(x),1);
    x=nt_vecadd(x,-mn);
else
    w=nt_unfold(w);
    if size(w,1)~=size(x,1)
        error('X and W should have same nrows');
    end
    if size(w,2)==1;
        mn=sum(nt_vecmult(double(x),w),1) ./ (sum(w,1)+eps);
    elseif size(w,2)==n;
        mn=sum(x.*w) ./ (sum(w,1)+eps);
    else
        error('W should have same ncols as X, or else 1');
    end
    %y=bsxfun(@minus,x,mn);
    x=nt_vecadd(x,-mn);
end
x=nt_fold(x,m);