Description of nt_greetings
Home > NoiseTools > nt_greetings.m
nt_greetings
PURPOSE
nt_greetings - display message the first time the toolbox is used
SYNOPSIS
function nt_greetings(reset)
DESCRIPTION
nt_greetings - display message the first time the toolbox is used
CROSS-REFERENCE INFORMATION
This function calls:
nt_version
This function is called by:
nt_cca [A,B,R]=nt_cca(x,y,lags,C,m,thresh) - canonical correlation
nt_demean [y,mn]=nt_demean(x,w) - remove weighted mean over cols
nt_dss0 [todss,pwr1,pwr2]=nt_dss0(c0,c1,keep1,keep2) - dss from covariance
nt_fold y=fold(x,epochsize) - fold 2D to 3D
nt_multismooth z=nt_multismooth(x,smooth,alignment) - apply multiple smoothing kernels
nt_narrowband_scan A=nt_narrowband_scan(x,freqs,sr,Q,plotflag) - scan for narrowband components using DSS
nt_pca [z,idx]=nt_pca(x,shifts,nkeep,threshold,w) - time-shift pca
nt_peaky [tocomps,ii]=nt_peaky(c,x,T,nSmooth) - find components that maximize peakiness
nt_sgram [s,f,t]=nt_sgram(x,window,noverlap,nfft,sr,flags) - spectrogram
nt_smooth y=nt_smooth(x,T,nIterations,nodelayflag) - smooth by convolution with square window
nt_sns y=nt_sns(x,nneigbors,skip,w) - sensor noise suppression
nt_star [y,w,ww]=nt_star(x,thresh,closest,depth) - sensor noise suppression, new version
nt_tsr [y,idx,w]=nt_tsr(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_unfold y=nt_fold(x) - unfold 3D to 2D
SOURCE CODE
function nt_greetings(reset)
%nt_greetings - display message the first time the toolbox is used
persistent greeted
if nargin>0; greeted=reset; return; end
if isempty(greeted)
    display(' ')
    display(['NoiseTools, version ',nt_version]);
    display('http://audition.ens.fr/adc/NoiseTools');
    display('Please cite relevant methods papers.');
    display(' ');
    greeted=1;
end